### ISSUE TITLE
Irregular redirect if there is no / at the end of the URL

### ISSUE THREAD

**Issue by mats16** [typester/gate#13]
about #11

example

config.yml

```
proxy:
  - path: /es
    dest: http://127.0.0.1:9200
    strip_path: yes
```

access to:
`https://gate.example.com/es/_plugin/kopf`
redirect to:
`https://gate.example.com/_plugin/kopf/`

deleted path... `/es`
